---
- hosts: workstation

  tasks:
    - name: install mamp
      mac_pkg: pkg_name=de.appsolute.installer.mamp.pkg pkg_version=3.0.6
               url=MAMP
http://downloads.mamp.info/MAMP-PRO/releases/3.0.6/MAMP_MAMP_PRO_3.0.6.pkg
               archive_type=pkg archive_path=MAMP_MAMP_PRO_3.0.6.pkg

